// This file is part of Substrate.

// Copyright (C) 2021 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated voter bag thresholds.
//!
//! Generated on 2021-07-05T09:17:40.469754927+00:00
//! for the node runtime.

/// Existential weight for this runtime.
#[cfg(any(test, feature = "std"))]
#[allow(unused)]
pub const EXISTENTIAL_WEIGHT: u64 = 100_000_000_000_000;

/// Constant ratio between bags for this runtime.
#[cfg(any(test, feature = "std"))]
#[allow(unused)]
pub const CONSTANT_RATIO: f64 = 1.0628253590743408;

/// Upper thresholds delimiting the bag list.
pub const THRESHOLDS: [u64; 200] = [
    100_000_000_000_000,
    106_282_535_907_434,
    112_959_774_389_150,
    120_056_512_776_105,
    127_599_106_300_477,
    135_615_565_971_369,
    144_135_662_599_590,
    153_191_037_357_827,
    162_815_319_286_803,
    173_044_250_183_800,
    183_915_817_337_347,
    195_470_394_601_017,
    207_750_892_330_229,
    220_802_916_738_890,
    234_674_939_267_673,
    249_418_476_592_914,
    265_088_281_944_639,
    281_742_548_444_211,
    299_443_125_216_738,
    318_255_747_080_822,
    338_250_278_668_647,
    359_500_973_883_001,
    382_086_751_654_776,
    406_091_489_025_036,
    431_604_332_640_068,
    458_720_029_8